[buildPlans.CuteDracula]
family = "CuteDracula"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.CuteDracula.variants.design]
one = "base"
four = "closed-serifless"
five = "oblique-arched-serifless"
six = "open-contour"
seven = "bend-serifless"
eight = "crossing-asymmetric"
nine = "open-contour"
zero = "oval-dotted"
capital-a = "round-top-serifless"
capital-d = "more-rounded-serifless"
capital-f = "serifless"
capital-g = "toothless-corner-serifless-hookless"
capital-k = "symmetric-touching-serifless"
capital-m = "hanging-serifless"
a = "double-storey-toothless-rounded"
b = "toothless-corner-serifless"
d = "toothless-corner-serifless"
e = "flat-crossbar"
f = "flat-hook-serifless"
g = "single-storey-earless-rounded"
i = "serifed-semi-tailed"
k = "symmetric-touching-serifless"
l = "serifed-semi-tailed"
m = "short-leg-tailed-serifed"
n = "earless-corner-straight-serifless"
p = "earless-rounded-serifless"
q = "earless-corner-straight-serifless"
r = "earless-corner-serifless"
t = "bent-hook-asymmetric"
u = "toothless-corner-serifless"
y = "cursive-serifless"
z = "cursive"
capital-eszet = "rounded-serifless"
eszet = "longs-s-lig-serifless"
lower-alpha = "barred-earless-corner-tailed"
capital-gamma = "bottom-serifed"
lower-eta = "earless-corner-serifless"
lower-kappa = "symmetric-touching-serifless"
lower-lambda = "straight-turn"
lower-mu = "toothless-corner-serifless"
lower-nu = "straight"
lower-xi = "rounded"
lower-pi = "small-capital"
lower-upsilon = "straight-serifless"
lower-phi = "neo-hellenic"
lower-psi = "flat-top-serifless"
partial-derivative = "closed-contour"
cyrl-a = "double-storey-tailed"
cyrl-capital-zhe = "symmetric-touching"
cyrl-zhe = "symmetric-touching"
cyrl-capital-ka = "symmetric-touching-serifless"
cyrl-ka = "symmetric-touching-serifless"
cyrl-em = "slanted-sides-hanging-serifless"
cyrl-capital-u = "straight-turn-serifless"
cyrl-u = "straight-turn-serifless"
underscore = "low"
paren = "large-contour"
brace = "straight"
guillemet = "straight"
number-sign = "slanted"
dollar = "open"
cent = "open"
percent = "rings-continuous-slash"
pilcrow = "low"
micro-sign = "toothless-corner-serifless"
lig-ltgteq = "slanted"
lig-neq = "slightly-slanted-dotted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.CuteDracula.variants.italic]
one = "base"
four = "closed-serifless"
five = "oblique-arched-serifless"
six = "open-contour"
seven = "bend-serifless"
eight = "crossing-asymmetric"
nine = "open-contour"
zero = "oval-dotted"
capital-a = "round-top-serifless"
capital-d = "more-rounded-serifless"
capital-f = "serifless"
capital-g = "toothless-corner-serifless-hookless"
capital-k = "symmetric-touching-serifless"
capital-m = "hanging-motion-serifed"
a = "double-storey-toothless-rounded"
b = "toothless-corner-serifless"
d = "toothless-corner-serifless"
e = "flat-crossbar"
f = "flat-hook-tailed"
g = "single-storey-earless-rounded"
i = "serifed"
k = "symmetric-touching-serifless"
l = "serifed-semi-tailed"
m = "earless-rounded-double-arch-short-leg-tailed-serifless"
n = "earless-corner-straight-serifless"
p = "earless-rounded-serifless"
q = "earless-corner-straight-serifless"
r = "earless-corner-serifless"
t = "bent-hook-asymmetric"
u = "toothless-corner-serifless"
y = "cursive-serifless"
z = "cursive"
capital-eszet = "rounded-serifless"
eszet = "longs-s-lig-serifless"
lower-alpha = "barred-earless-corner-tailed"
capital-gamma = "bottom-serifed"
lower-eta = "earless-corner-serifless"
lower-kappa = "symmetric-touching-serifless"
lower-lambda = "straight-turn"
lower-mu = "toothless-corner-serifless"
lower-nu = "straight"
lower-xi = "rounded"
lower-pi = "small-capital"
lower-upsilon = "straight-serifless"
lower-phi = "neo-hellenic"
lower-psi = "flat-top-serifless"
partial-derivative = "closed-contour"
cyrl-a = "double-storey-tailed"
cyrl-capital-zhe = "symmetric-touching"
cyrl-zhe = "symmetric-touching"
cyrl-capital-ka = "symmetric-touching-serifless"
cyrl-ka = "symmetric-touching-serifless"
cyrl-em = "slanted-sides-hanging-serifless"
cyrl-capital-u = "straight-turn-serifless"
cyrl-u = "straight-turn-serifless"
underscore = "low"
brace = "straight"
guillemet = "straight"
number-sign = "slanted"
dollar = "open"
cent = "open"
percent = "rings-continuous-slash"
bar = "force-upright"
pilcrow = "low"
micro-sign = "toothless-corner-serifless"
lig-ltgteq = "slanted"
lig-neq = "slightly-slanted-dotted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.CuteDracula.ligations]
inherits = "dlig"

[buildPlans.CuteDracula.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.CuteDracula.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.CuteDracula.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.CuteDracula.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.CuteDracula.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.CuteDracula.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.CuteDracula.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.CuteDracula.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.CuteDracula.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.CuteDracula.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"